
language: node_js
node_js:
    - "12"
dist: trusty
addons:
    chrome: stable
    sonarcloud:
      organization: "adrianofelisberto"
      token: $SONARCLOUD_ACCESS_TOKEN
branches:
  only:
    - master
    - develop

before_script:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run sonar

skip_cleanup: true
on:
  branch: master

before_deploy:
  - npm run build

deploy:
  provider: netlify
  site: $NETLIFY_SITE_ID
  auth: $NETLIFY_ACCESS_TOKEN
  dir: dist
  edge: true
